name: Portfolio Deployment

on:
  push:
    branches: [ "master" ]

jobs:
  deploy:
    runs-on: [self-hosted, linux]  # Ensure this is a Linux server or a self-hosted runner

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v4
    
    # Clean previous builds
    - name: Clean previous builds
      run: |
        rm -rf .next
        rm -rf node_modules
    
    # Deploy to VPS via Git
    - name: Clone or Pull Repository
      run: |
          if [ ! -d "${{vars.REPO_DIRECTORY}}" ]; then
            echo "Repository not found. Cloning..."
            git clone git@github.com:${{ github.repository }}.git "${{vars.REPO_DIRECTORY}}"
          else
            echo "Repository exists. Pulling latest changes..."
            cd "${{vars.REPO_DIRECTORY}}" 
            git reset --hard HEAD
            git pull origin master
          fi

    # Install production dependencies and build the project on VPS
    - name: Install production dependencies and build project on VPS
      run: |
          cd ${{ vars.PROJECT_PATH }}
          npm ci
          npm install --production
          npm run build

    # Run Application
    - name: Run Application on VPS
      run: |
       sudo systemctl restart diegoiglesiasdiaz.service
       sudo systemctl status diegoiglesiasdiaz.service
